### ISSUE TITLE
nonebot更新rc1后 插件报错

### ISSUE THREAD

**Issue by 1717tian** [AkashiCoin/nonebot_plugin_mockingbird#21]
Traceback (most recent call last):                                                                                        File "E:\zhenxun_bot\bot.py", line 15, in <module>                                                                        nonebot.load_plugins("extensive_plugin")                                                                              File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-X7m5lqsL-py3.9\lib\site-packages\nonebot\plugin\load.py", line 45, in load_plugins                                                                              return manager.load_all_plugins()                                                                                     File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-X7m5lqsL-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins                                                                      return set(                                                                                                           File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-X7m5lqsL-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>                                                                             filter(None, (self.load_plugin(name) for name in self.available_plugins))                                           > File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-X7m5lqsL-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin                                                                           module = importlib.import_module(                                                                                     File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module                                                                                                                        return _bootstrap._gcd_import(name[level:], package, level)                                                           File "<frozen importlib._bootstrap>", line 1030, in _gcd_import                                                         File "<frozen importlib._bootstrap>", line 1007, in _find_and_load                                                      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked                                              File "<frozen importlib._bootstrap>", line 680, in _load_unlocked                                                       File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-X7m5lqsL-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module                                                                           super().exec_module(module)                                                                                           File "<frozen importlib._bootstrap_external>", line 850, in exec_module                                                 File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed                                            File "E:\zhenxun_bot\extensive_plugin\nonebot_plugin_mockingbird\__init__.py", line 10, in <module>                       from nonebot import Driver, export, on_command                                                                      ImportError: cannot import name 'export' from 'nonebot' (C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-X7m5lqsL-py3.9\lib\site-packages\nonebot\__init__.py)

**Comment by 1717tian** [comment]
删除了export相关调用后 插件运行正常

**Comment by wlz-remake** [comment]
我也是这个问题，如果修好了踹我（）

**Comment by wlz-remake** [comment]
> 删除了export相关调用后 插件运行正常

只需要删除含有export字段的代码 插件就能正常运行了吗

**Comment by 1717tian** [comment]
> > 删除了export相关调用后 插件运行正常
> 
> 只需要删除含有export字段的代码 插件就能正常运行了吗

是的 这边跑了半个月 没异常报错
